### Libraries

In [49]:
!pip install seaborn
!pip install ydata-profiling

Requirement already satisfied: seaborn in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from seaborn) (1.25.2)
Requirement already satisfied: pandas>=0.25 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from seaborn) (2.1.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from seaborn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.12.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.43.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Requirement already satisfied: ydata-profiling in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (4.6.4)
Requirement already satisfied: scipy<1.12,>=1.4.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (1.11.3)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (2.1.1)
Requirement already satisfied: matplotlib<3.9,>=3.2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (3.8.0)
Requirement already satisfied: pydantic>=2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (2.4.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (3.1.2)
Requirement already satisfied: visions[type_image_path]==0.7.5 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.7.5)
Requirement already satisfied: numpy<1.26,>=1.16.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (1.25.2)
Requirement already satisfied: htmlmin==0.1.12 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (4.66.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (1.11)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.14.1)
Requirement already satisfied: typeguard<5,>=4.1.2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (4.1.5)
Requirement already satisfied: imagehash==4.3.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (1.9.3)
Requirement already satisfied: dacite>=1.8 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (1.8.1)
Requirement already satisfied: numba<0.59.0,>=0.56.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from ydata-profiling) (0.58.1)
Requirement already satisfied: PyWavelets in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling) (1.5.0)
Requirement already satisfied: pillow in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling) (10.0.1)
Requirement already satisfied: attrs>=19.3.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling) (3.1)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (0.12.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (4.43.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from matplotlib<3.9,>=3.2->ydata-profiling) (2.8.2)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from numba<0.59.0,>=0.56.0->ydata-profiling) (0.41.1)
Requirement already satisfied: pytz>=2020.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.3.2)
Requirement already satisfied: annotated-types>=0.4.0 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling) (0.5.0)
Requirement already satisfied: pydantic-core==2.10.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling) (2.10.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2023.7.22)

Requirement already satisfied: patsy>=0.5.4 in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (0.5.6)
Requirement already satisfied: six in /home/imran/anaconda3/envs/huggingface/lib/python3.11/site-packages (from patsy>=0.5.4->statsmodels<1,>=0.13.2->ydata-profiling) (1.16.0)

In [50]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport
from prices import *

from datetime import datetime, timedelta

### Data Loading

In [51]:
df = pd.read_csv("data/electrodatos.csv")
df.head(5)

,Código universal de punto de suministro,Fecha,Hora,Consumo,Método de obtención,datetime
0,0,2021-08-03,1,0.100,Real,2021-08-03 01:00:00
1,0,2021-08-03,2,0.073,Real,2021-08-03 02:00:00
2,0,2021-08-03,3,0.083,Real,2021-08-03 03:00:00
3,0,2021-08-03,4,0.073,Real,2021-08-03 04:00:00
4,0,2021-08-03,5,0.073,Real,2021-08-03 05:00:00

### Rename Column Names

In [52]:
# New column names
new_column_names = ['UserID', 'Date', 'Hour', 'Consumption_KWh', 'Method', 'Datetime']

# Rename columns
df.columns = new_column_names
df.head(24)

    UserID        Date  Hour  Consumption_KWh Method             Datetime
0        0  2021-08-03     1            0.100   Real  2021-08-03 01:00:00
1        0  2021-08-03     2            0.073   Real  2021-08-03 02:00:00
2        0  2021-08-03     3            0.083   Real  2021-08-03 03:00:00
3        0  2021-08-03     4            0.073   Real  2021-08-03 04:00:00
4        0  2021-08-03     5            0.073   Real  2021-08-03 05:00:00
5        0  2021-08-03     6            0.078   Real  2021-08-03 06:00:00
6        0  2021-08-03     7            0.077   Real  2021-08-03 07:00:00
7        0  2021-08-03     8            0.076   Real  2021-08-03 08:00:00
8        0  2021-08-03     9            0.479   Real  2021-08-03 09:00:00
9        0  2021-08-03    10            0.214   Real  2021-08-03 10:00:00
10       0  2021-08-03    11            0.200   Real  2021-08-03 11:00:00
11       0  2021-08-03    12            0.211   Real  2021-08-03 12:00:00
12       0  2021-08-03    13            0.182   Real  2021-08-03 13:00:00
13       0  2021-08-03    14            0.228   Real  2021-08-03 14:00:00
14       0  2021-08-03    15            0.151   Real  2021-08-03 15:00:00
15       0  2021-08-03    16            0.192   Real  2021-08-03 16:00:00
16       0  2021-08-03    17            0.194   Real  2021-08-03 17:00:00
17       0  2021-08-03    18            0.221   Real  2021-08-03 18:00:00
18       0  2021-08-03    19            0.327   Real  2021-08-03 19:00:00
19       0  2021-08-03    20            0.341   Real  2021-08-03 20:00:00
20       0  2021-08-03    21            0.233   Real  2021-08-03 21:00:00
21       0  2021-08-03    22            0.237   Real  2021-08-03 22:00:00
22       0  2021-08-03    23            0.274   Real  2021-08-03 23:00:00
23       0  2021-08-03    24            0.216   Real  2021-08-04 00:00:00

In [53]:
df['Method'] = df['Method'].replace({'Real': 'R', 'Estimado': 'E'})

### Feature Engineering

In [54]:
# Convert 'Date' and 'Datetime' columns to datetime objects
df['Date'] = pd.to_datetime(df['Date'])
df['Datetime'] = pd.to_datetime(df['Datetime'])

# Extract additional features
df['Day_of_Week'] = df['Date'].dt.dayofweek
df['Time_of_Day'] = pd.cut(df['Datetime'].dt.hour, bins=[-1, 6, 12, 18, 23], labels=['Night', 'Morning', 'Afternoon', 'Evening'])
#df['Load_Type'] = pd.cut(df['Datetime'].dt.hour, bins=[-1, 6, 18, 23], labels=['Off-Peak Load', 'Peak Load', 'Off-Peak Load'], ordered=False)
df['Season'] = (df['Date'].dt.month % 12 + 3) // 3


# Encode categorical variable 'Method' using one-hot encoding
#df = pd.get_dummies(df, columns=['Method'])

df.head(24)

,UserID,Date,Hour,Consumption_KWh,Method,Datetime,Day_of_Week,Time_of_Day,Season
0,0,2021-08-03,1,0.100,R,2021-08-03 01:00:00,1,Night,3
1,0,2021-08-03,2,0.073,R,2021-08-03 02:00:00,1,Night,3
2,0,2021-08-03,3,0.083,R,2021-08-03 03:00:00,1,Night,3
3,0,2021-08-03,4,0.073,R,2021-08-03 04:00:00,1,Night,3
4,0,2021-08-03,5,0.073,R,2021-08-03 05:00:00,1,Night,3
5,0,2021-08-03,6,0.078,R,2021-08-03 06:00:00,1,Night,3
6,0,2021-08-03,7,0.077,R,2021-08-03 07:00:00,1,Morning,3
7,0,2021-08-03,8,0.076,R,2021-08-03 08:00:00,1,Morning,3
8,0,2021-08-03,9,0.479,R,2021-08-03 09:00:00,1,Morning,3
9,0,2021-08-03,10,0.214,R,2021-08-03 10:00:00,1,Morning,3
10,0,2021-08-03,11,0.200,R,2021-08-03 11:00:00,1,Morning,3
11,0,2021-08-03,12,0.211,R,2021-08-03 12:00:00,1,Morning,3
12,0,2021-08-03,13,0.182,R,2021-08-03 13:00:00,1,Afternoon,3
13,0,2021-08-03,14,0.228,R,2021-08-03 14:00:00,1,Afternoon,3
14,0,2021-08-03,15,0.151,R,2021-08-03 15:00:00,1,Afternoon,3
15,0,2021-08-03,16,0.192,R,2021-08-03 16:00:00,1,Afternoon,3
16,0,2021-08-03,17,0.194,R,2021-08-03 17:00:00,1,Afternoon,3
17,0,2021-08-03,18,0.221,R,2021-08-03 18:00:00,1,Afternoon,3
18,0,2021-08-03,19,0.327,R,2021-08-03 19:00:00,1,Evening,3
19,0,2021-08-03,20,0.341,R,2021-08-03 20:00:00,1,Evening,3
20,0,2021-08-03,21,0.233,R,2021-08-03 21:00:00,1,Evening,3
21,0,2021-08-03,22,0.237,R,2021-08-03 22:00:00,1,Evening,3
22,0,2021-08-03,23,0.274,R,2021-08-03 23:00:00,1,Evening,3
23,0,2021-08-03,24,0.216,R,2021-08-04 00:00:00,1,Night,3

In [55]:
from datetime import datetime, timedelta
mask = df['Hour'] == 24

df.loc[mask, 'Datetime'] = df['Datetime'] - timedelta(days=1)
df.head(24)

,UserID,Date,Hour,Consumption_KWh,Method,Datetime,Day_of_Week,Time_of_Day,Season
0,0,2021-08-03,1,0.100,R,2021-08-03 01:00:00,1,Night,3
1,0,2021-08-03,2,0.073,R,2021-08-03 02:00:00,1,Night,3
2,0,2021-08-03,3,0.083,R,2021-08-03 03:00:00,1,Night,3
3,0,2021-08-03,4,0.073,R,2021-08-03 04:00:00,1,Night,3
4,0,2021-08-03,5,0.073,R,2021-08-03 05:00:00,1,Night,3
5,0,2021-08-03,6,0.078,R,2021-08-03 06:00:00,1,Night,3
6,0,2021-08-03,7,0.077,R,2021-08-03 07:00:00,1,Morning,3
7,0,2021-08-03,8,0.076,R,2021-08-03 08:00:00,1,Morning,3
8,0,2021-08-03,9,0.479,R,2021-08-03 09:00:00,1,Morning,3
9,0,2021-08-03,10,0.214,R,2021-08-03 10:00:00,1,Morning,3
10,0,2021-08-03,11,0.200,R,2021-08-03 11:00:00,1,Morning,3
11,0,2021-08-03,12,0.211,R,2021-08-03 12:00:00,1,Morning,3
12,0,2021-08-03,13,0.182,R,2021-08-03 13:00:00,1,Afternoon,3
13,0,2021-08-03,14,0.228,R,2021-08-03 14:00:00,1,Afternoon,3
14,0,2021-08-03,15,0.151,R,2021-08-03 15:00:00,1,Afternoon,3
15,0,2021-08-03,16,0.192,R,2021-08-03 16:00:00,1,Afternoon,3
16,0,2021-08-03,17,0.194,R,2021-08-03 17:00:00,1,Afternoon,3
17,0,2021-08-03,18,0.221,R,2021-08-03 18:00:00,1,Afternoon,3
18,0,2021-08-03,19,0.327,R,2021-08-03 19:00:00,1,Evening,3
19,0,2021-08-03,20,0.341,R,2021-08-03 20:00:00,1,Evening,3
20,0,2021-08-03,21,0.233,R,2021-08-03 21:00:00,1,Evening,3
21,0,2021-08-03,22,0.237,R,2021-08-03 22:00:00,1,Evening,3
22,0,2021-08-03,23,0.274,R,2021-08-03 23:00:00,1,Evening,3
23,0,2021-08-03,24,0.216,R,2021-08-03 00:00:00,1,Night,3

### Get Electiricity Cost

In [ ]:
from tqdm.notebook import tqdm
tqdm.pandas()

prev_date = None
prev_response = None
def get_hourly_cost(date):
    global prev_response
    global prev_date
    only_date = str(date).split(" ")
    if str(only_date[0]) != str(prev_date):
        prev_date = only_date[0]
        #only_date = str(date).split(" ")
        day_costs = get_electricity_cost(only_date[0])
        #print(day_costs)
        single_hour = date.hour
        #print(single_hour)
        hourly_cost = day_costs[single_hour]
        prev_response = day_costs
    else:
        single_hour = date.hour
        #print(single_hour)
        hourly_cost = prev_response[single_hour]
    return hourly_cost

df['electricity_cost'] = df['Datetime'].progress_apply(get_hourly_cost)
df.head(24)

  0%|          | 0/145943 [00:00<?, ?it/s]

In [ ]:
# Calculate seasonal factors (assuming 4 seasons)
seasonal_factors = {
    'Spring': 1.1,
    'Summer': 1.2,
    'Fall': 1.1,
    'Winter': 1.3
}

def get_season(month):
    if 3 <= month <= 5:
        return 'Spring'
    elif 6 <= month <= 8:
        return 'Summer'
    elif 9 <= month <= 11:
        return 'Fall'
    else:
        return 'Winter'
    
def get_season_name(date):
    month = (date.month % 12 + 3)
    season = get_season(month)
    return season

# Apply seasonal factors
def apply_seasonal_factor(date):
    month = date.month // 4  # Simplified approach to determine season
    season = get_season(month)
    return seasonal_factors[season]

df['season'] = df['Datetime'].dt.date.apply(get_season_name)

In [ ]:
def categorize_hour(timestamp):
    if timestamp.dayofweek < 5:  # Monday to Friday (business days)
        if 0 <= timestamp.hour < 8:
            return 'Off-Peak Hours'
        elif 8 <= timestamp.hour < 10 or 14 <= timestamp.hour < 18 or 22 <= timestamp.hour <= 23:
            return 'Mid-Peak Hours'
        else:
            return 'Peak Hours'
    else:  # Saturdays and Sundays
        return 'Off-Peak Hours'

# Applying the function to categorize each hour
df['usage_category'] = df['Datetime'].apply(categorize_hour)

# Displaying the DataFrame with the usage category information
df.head(24)

### Store preprocessed data into CSV and Excel

In [42]:
df.to_excel("data/cleaned_preprocessed_data.xlsx")
df.to_csv("data/cleaned_preprocessed_data.csv")

In [ ]:
print("Preprocessed Data Files have been saved")